//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Khanh.DuLieu
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhanvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nhanvien()
        {
            this.hopdonglaodong = new HashSet<hopdonglaodong>();
        }
    
        public string ma { get; set; }
        public string ten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string quequan { get; set; }
        public Nullable<bool> gioitinh { get; set; }
        public string email { get; set; }
        public string dienthoai { get; set; }
        public string dantoc { get; set; }
        public string phongbanma { get; set; }
        public string chucvuma { get; set; }
        public string trinhdoma { get; set; }
        public Nullable<long> bacluongma { get; set; }
        public string ghichu { get; set; }
    
        public virtual chucvu chucvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hopdonglaodong> hopdonglaodong { get; set; }
        public virtual luong luong { get; set; }
        public virtual phongban phongban { get; set; }
        public virtual trinhdohocvan trinhdohocvan { get; set; }
    }
}
